### PR TITLE
Make the script less platform-dependant / Some minor improvements

### PR DESCRIPTION
**Pull request by nonatomiclabs**
Changes:
- Replace OS-dependant paths / Exit script on Windows
- Replace default mode of open_file() function
- Add MIT license which I find often used across projects

### CODE REVIEW

**Comment by darthlukan** [comment]
Wow! Thank you very much for this, it looks great :+1:

**Comment by nonatomiclabs** [comment]
You're welcome :)
By the way, do you know about [this repo](https://github.com/audreyr/cookiecutter)?
Is it not kind of the same thing that you want to achieve?
If not, it may be worth updating the README to have a better description of the project :)

**Comment by darthlukan** [comment]
I had not seen that before you linked it.  I just updated the README to reflect the current state as well as more details.  That tool looks great, but templates are still more complicated than a Progeny footprint :)

**Comment by nonatomiclabs** [comment]
All right, thanks! :)

**Pull request merged**
